-- Q.1) What is the most common room type in NYC Airbnb listings?
SELECT room_type, Count(*) as co
FROM room_types
GROUP BY 1
ORDER BY co DESC

-- Q.2) What is the average price of a listing by room type?

SELECT avg(p.price) as avg_price, r.room_type
FROM prices as p
LEFT JOIN room_types as r
USING (listing_id)
GROUP BY 2
ORDER BY avg_price DESC

-- Q.3) Which borough has the highest average price per month?
SELECT avg(p.price) as avg_price, p.borough
FROM prices as p
LEFT JOIN room_types as r
USING (listing_id)
GROUP BY 2
ORDER BY avg_price DESC

-- Q.4)How many listings of each room type are in each borough?

SELECT  p.borough, r.room_type, COUNT(*) as type
FROM prices as p
LEFT JOIN room_types as r
USING (listing_id)
GROUP BY 1,2 

-- Q.5) How many listings in each room type category have a price of over $500 per night?

SELECT  r.room_type, COUNT(*) as type
FROM prices as p
LEFT JOIN room_types as r
USING (listing_id)
WHERE price > 500
GROUP BY 1;

-- Q.6) What is the distribution of listing prices by neighborhood?

SELECT borough, MIN(price) as min_price, MAX(price) as max_price, AVG(price) as avg_price
FROM prices
GROUP BY 1

-- Q.7) What is the estimated amount of revenue generated by hosts in each borough?

SELECT p.borough, SUM(p.price * r.booked_days_365)  as total
FROM prices as p
LEFT JOIN reviews as r
USING (listing_id)
GROUP BY borough

-- Q.8) What is the average price per month for listings in each neighborhood?

SELECT  p.neighbourhood, r.room_type, AVG(price_per_month)
FROM prices as p
LEFT JOIN room_types as r
USING (listing_id)
GROUP BY 2,1
ORDER BY 3 DESC
